[project]
name = "empa-ftp-upload"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client>=1.49.0",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "toml>=0.10.2",
]
